const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const axios = require('axios');

router.post('/', async (req, res) => {
  try {
    const {
      materials,
      labourHours,
      hourlyRate,
      marginPercent,
      designImageUrl,
    } = req.body;

    if (!materials || !designImageUrl) {
      return res.status(400).json({ error: 'Materials and design image are required' });
    }

    // Create PDF
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.set({
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="george-quote.pdf"',
        'Content-Length': pdfBuffer.length,
      });
      res.send(pdfBuffer);
    });

    // Download and embed the design image
    try {
      const imageResponse = await axios.get(designImageUrl, {
        responseType: 'arraybuffer',
      });
      const imageBuffer = Buffer.from(imageResponse.data);
      doc.image(imageBuffer, 50, 50, { width: 500 });
      doc.moveDown(12);
    } catch {
      doc.moveDown(2);
    }

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('GEORGE', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Landscaping Quote', { align: 'center' });
    doc.moveDown();

    // Divider
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Materials table
    doc.fontSize(10).font('Helvetica-Bold');
    doc.text('Material', 50, doc.y, { width: 200 });
    doc.text('Qty', 250, doc.y - 12, { width: 80 });
    doc.text('Unit Price', 330, doc.y - 12, { width: 100 });
    doc.text('Total', 430, doc.y - 12, { width: 100 });
    doc.moveDown(0.5);

    doc.font('Helvetica');
    let materialsTotal = 0;

    materials.forEach((item) => {
      const lineTotal = item.selectedPrice * item.qty;
      materialsTotal += lineTotal;
      const y = doc.y;
      doc.text(`${item.name} (${item.unit})`, 50, y, { width: 200 });
      doc.text(`${item.qty}`, 250, y, { width: 80 });
      doc.text(`£${item.selectedPrice.toFixed(2)}`, 330, y, { width: 100 });
      doc.text(`£${lineTotal.toFixed(2)}`, 430, y, { width: 100 });
      doc.moveDown(0.5);
    });

    // Labour
    const labourTotal = labourHours * hourlyRate;
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold');
    doc.text(`Labour (${labourHours} hrs @ £${hourlyRate}/hr)`, 50, doc.y, { width: 380 });
    doc.text(`£${labourTotal.toFixed(2)}`, 430, doc.y - 12, { width: 100 });
    doc.moveDown();

    // Total with margin
    const subtotal = materialsTotal + labourTotal;
    const total = subtotal * (1 + marginPercent / 100);
    doc.fontSize(14);
    doc.text('TOTAL', 50, doc.y, { width: 380 });
    doc.text(`£${total.toFixed(2)}`, 430, doc.y - 18, { width: 100 });
    doc.moveDown(2);

    // Footer
    doc.fontSize(10).font('Helvetica').fillColor('grey');
    doc.text('Quote generated by George — Landscaping Quoting Tool', {
      align: 'center',
    });

    doc.end();

  } catch (error) {
    console.error('generatePdf error:', error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;